[package]
name = "lucide-rust"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []

# Framework features
dioxus = ["dep:dioxus"]
leptos = ["dep:leptos"]
yew = ["dep:yew"]
sycamore = ["dep:sycamore"]
codegen = ["dep:quick-xml", "dep:regex", "dep:convert_case", "dep:serde", "dep:serde_json"]

# Icon category features for bundle size optimization
accessibility = []
account = []
animals = []
arrows = []
brands = []
buildings = []
charts = []
communication = []
connectivity = []
cursors = []
design = []
development = []
devices = []
emoji = []
files = []
finance = []
food-beverage = []
gaming = []
home = []
layout = []
mail = []
math = []
medical = []
multimedia = []
nature = []
navigation = []
notifications = []
people = []
photography = []
science = []
seasons = []
security = []
shapes = []
shopping = []
social = []
sports = []
sustainability = []
text = []
time = []
tools = []
transportation = []
travel = []
weather = []

# Meta features
all-icons = [
    "accessibility",
    "account",
    "animals",
    "arrows",
    "brands",
    "buildings",
    "charts",
    "communication",
    "connectivity",
    "cursors",
    "design",
    "development",
    "devices",
    "emoji",
    "files",
    "finance",
    "food-beverage",
    "gaming",
    "home",
    "layout",
    "mail",
    "math",
    "medical",
    "multimedia",
    "nature",
    "navigation",
    "notifications",
    "people",
    "photography",
    "science",
    "seasons",
    "security",
    "shapes",
    "shopping",
    "social",
    "sports",
    "sustainability",
    "text",
    "time",
    "tools",
    "transportation",
    "travel",
    "weather",
]

# Common combinations for convenience
essentials = ["arrows", "navigation", "files", "communication"]
web-app = ["arrows", "navigation", "files", "communication", "layout", "notifications"]
mobile-app = ["arrows", "navigation", "communication", "multimedia", "account"]
[dependencies]
# Shared deps
once_cell = "1"
serde = { version = "1", features = ["derive"], optional = true }

# Code generation deps (dev dependencies)
quick-xml = { version = "0.36", optional = true }
regex = { version = "1.10", optional = true }
convert_case = { version = "0.6", optional = true }
serde_json = { version = "1.0", optional = true }
chrono = { version = "0.4", optional = true, default-features = false, features = ["clock"] }

# Framework deps (optional and feature-gated)
dioxus = { version = "0.6", optional = true }
leptos = { version = "0.8", optional = true, default-features = false, features = ["csr"] }
yew = { version = "0.21", optional = true, default-features = false, features = ["csr"] }
sycamore = { version = "0.9", optional = true }

[package.metadata.docs.rs]
# Build docs with all features for completeness
all-features = true

[lib]
name = "lucide_rust"
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "generate-icons"
path = "src/bin/generate-icons.rs"
required-features = ["codegen"]