[build]
target = "index.html"
dist = "dist"
public_url = "/"
filehash = true

[watch]
watch = ["src", "public"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 3000
open = false

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
  "tailwindcss",
  "--input", "./public/style.css",
  "--output", "./public/output.css"
]
