# GitHub Issue Template Configuration
#
# This file configures the issue creation experience on GitHub.
# It provides helpful links to users before they create new issues.
#

blank_issues_enabled: false