# GitHub Issue Template Configuration
#
# This file configures the issue creation experience on GitHub.
# It provides helpful links to users before they create new issues.
#

blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/vaclavhrach/lucide-rs/discussions
    about: Ask questions, share ideas, or discuss the project with the community

  - name: 📚 Documentation
    url: https://github.com/vaclavhrach/lucide-rs#readme
    about: Check out the documentation and examples in the README

  - name: 🎨 Icon Library
    url: https://lucide.dev
    about: Browse the complete Lucide icon library

  - name: 🔧 Examples
    url: https://github.com/vaclavhrach/lucide-rs/tree/main/apps/examples
    about: View example implementations for different frameworks
