name: 📚 Documentation Improvement
description: Request improvements to documentation, guides, or examples
title: "[Docs]: "
labels: ["documentation", "enhancement"]
assignees: []
body:
  - type: textarea
    id: area
    attributes:
      label: Docs area
      placeholder: README, ICONS.md, examples, API, etc.
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: What should be improved?
      placeholder: Missing info, unclear section, broken link, etc.
    validations:
      required: true
    attributes:
      label: Current Documentation State
      description: What is currently documented (if anything) and where?
      placeholder: |
        - Current location: README.md or docs/...
        - What's currently documented: ...
        - What's missing or incorrect: ...

  - type: textarea
    id: requested_improvement
    attributes:
      label: Requested Improvement
      description: What specific improvements would you like to see?
      placeholder: |
        Describe what you'd like to see documented or improved:
        - What information should be added?
        - How should it be organized?
        - What examples would be helpful?
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case/Context
      description: When would someone need this documentation?
      placeholder: |
        Describe the scenario where this documentation would be needed:
        - What task is the user trying to accomplish?
        - What is their experience level?
        - Where in their workflow would they need this info?
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      multiple: true
      options:
        - Complete beginners
        - Rust beginners
        - Experienced Rust developers
        - Web framework users
        - Icon library users
        - Contributors/maintainers
        - Library authors

  - type: textarea
    id: proposed_content
    attributes:
      label: Proposed Content (Optional)
      description: If you have ideas for the actual content, share them here
      placeholder: |
        Draft content, outline, or examples you'd like to see:

        ## Example Section Title

        Explanation of concept...

        ```rust
        // Example icon usage
        <lucide::Home class="w-6 h-6" />
        ```

  - type: textarea
    id: examples
    attributes:
      label: Helpful Examples
      description: What examples would make this documentation more useful?
      placeholder: |
        Examples that would be helpful:
        - Code snippets
        - Command examples
        - Common patterns
        - Real-world use cases

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation improvement?
      options:
        - Low - Nice to have
        - Medium - Would help users
        - High - Important for user experience
        - Critical - Blocking user adoption
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Links to similar documentation in other projects
        - References or resources that might be helpful
        - Any other context that might be useful

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in helping with this documentation?
      options:
        - label: I can help write the documentation
          required: false
        - label: I can provide examples and use cases
          required: false
        - label: I can review and test the documentation
          required: false
