name: 📋 Task
description: Create a task for project maintenance, improvements, or general work
title: "[Task]: "
labels: ["task"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: What needs to be done?
      placeholder: Short description of the task.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Done when
      placeholder: |
        - [ ] ...
        - [ ] ...

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Maintenance
        - Documentation
        - Testing
        - Refactoring
        - CI/CD
        - Other
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        List specific criteria that must be met:
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What areas of the project are affected?
      placeholder: |
        List affected areas:
        - Icon Library
        - Framework Integration
        - Documentation
        - Examples
        - CI/CD
        - Build System
        - etc.

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical considerations or constraints?
      placeholder: |
        Include any technical details:
        - Implementation considerations
        - Constraints or limitations
        - Dependencies
        - Performance requirements

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Links, references, or resources related to this task
      placeholder: |
        Include any helpful resources:
        - Documentation links
        - Related issues or PRs
        - External references
        - Examples from other projects

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much effort do you think this task will require?
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (3-7 days)
        - Extra Large (> 1 week)
        - Unknown

  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks (Optional)
      description: Break down the task into smaller subtasks
      placeholder: |
        List specific subtasks if applicable:
        - [ ] Subtask 1
        - [ ] Subtask 2
        - [ ] Subtask 3

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
      placeholder: Any additional context, considerations, or notes

  - type: checkboxes
    id: labels
    attributes:
      label: Additional Labels
      description: Should this task have additional labels?
      options:
        - label: Breaking change
          required: false
        - label: Good first issue
          required: false
        - label: Help wanted
          required: false
        - label: Documentation
          required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you planning to work on this task?
      options:
        - label: I plan to work on this task
          required: false
